defaults:
  batch_size: 1
  cfg_scale: 13
  height: 768
  n_iter: 1
  restore_faces: true
  sampler_name: Euler a
  seed: 10
  seed_resize_from_h: 10
  seed_resize_from_w: 10
  steps: 50
  styles: []
  subseed: 10
  width: 768
negative_prompt:
- ugly
- easynegative
- bad anatomy
- duplicate:2
- poorly drawn face
- out of frame
- extra limbs
- bad composition
- deformed
- ((face out of frame))
- bad anatomy
- watermark
- signature
- cut off
- low contrast
- underexposed
- text
- overexposed
style: photorealistic, film noir
